shoes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from shoes_app import views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", views.index_page, name="index"),
    path("about/", views.about_us, name="about"),
    path("search/", views.search, name="search"),

    path('accounts/', include('allauth.urls')),
    path("signup/", user_views.sign_up, name="signup"),

    path ('login/',user_views.CustomLoginView.as_view(
    template_name='users/login.html'),name="login"),

    path("logout/", auth_views.LogoutView.as_view(
    template_name='users/logout.html'), name="logout"),
    
    path('men/',views.men_shoes_page,name="men"),
    path('women/',views.women_shoes_page,name="women"),
    
    path('boots/',views.boots_page,name="boots"),
    path('sneakers/',views.sneakers_shoe_page,name="sneakers"),
    path('sports/',views.sports_shoe_page,name="sports"),


    path("password-reset/", user_views.password_reset_request, name="password_reset"),
        
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
    template_name='users/password_reset_done.html'
    ),name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    template_name="users/password_reset_confirm.html"
    ), name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
    template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    
    path("users/", include('users.urls')),
    path("shoes/", include('shoes_app.urls')),
        
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoes_app/urls.py
from django.urls import path
from shoes_app import views

app_name = 'shoes_app'

urlpatterns = [
    path('add-shoe/', views.AddShoe.as_view(), name='add_shoe'),
    path("<slug:slug>/", views.shoe_detail, name="shoe_detail"),
    path("<slug:slug>/edit-shoe/", views.edit_shoe, name="edit_shoe"),
    path('<slug:slug>/delete-shoe/', views.delete_shoe, name='delete_shoe'),

]

users/urls.py
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [  
    path('<str:username>/',user_views.Profile.as_view(),name="user_profile"),
    path('<str:username>/update-profile/',user_views.update_profile,name='update_profile'),
    path('<str:username>/change-password/', user_views.change_password, name='change_password'),
    path('<str:username>/delete-account/', user_views.delete_user, name='delete_user'),
    
]

users/models.py
from django.db import models
from django_resized import ResizedImageField
from django.contrib.auth.models import User
from shoes_app.models import Shoe

GENDER = [ ('Male', 'Male'), ('Female', 'Female'), ('not specified', 'Rather not say') ]

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'users/user_profile_images/user_{0}/{1}'.format(instance.user.id, filename)

class UserProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)   
    image = ResizedImageField(size=[320, 320], quality=99,
    crop=['middle', 'center'],
    upload_to=user_directory_path, 
    blank=True, null=True,
    default='users/user_default_img.png'
    )
    bio = models.TextField(blank=True)
    website = models.URLField(max_length=30,blank=True)
    gender = models.CharField(max_length=13,choices=GENDER,null=True)
    
    def __str__(self) -> str:
        return self.user.username


    

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from users.models import UserProfile

GENDER = [ ('Male', 'Male'), ('Female', 'Female'), ('Not specified', 'Rather not say') ]

User._meta.get_field('email')._unique = True

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    username = forms.CharField(
        label="Username",
        widget=forms.TextInput(attrs={
            'class':'username-field signup-fields', 
            'type':'text', 
            'align':'center', 
            'placeholder':'username'}),
    )
    email = forms.CharField(
        label="Email",
        widget=forms.EmailInput(attrs={
            'class':'email-field signup-fields', 
            'type':'email', 
            'align':'center', 
            'placeholder':'email'}),
    )

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={
            'class':'password1-field signup-fields', 
            'type':'password', 
            'align':'center', 
            'placeholder':'password'}),
    )
    password2 = forms.CharField(
        label="Confirm password",
        widget=forms.PasswordInput(attrs={
            'class':'password2-field signup-fields', 
            'type':'password', 
            'align':'center', 
            'placeholder':'password confirmation'}),
    )

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

        widgets = {
            'username': forms.TextInput(attrs={'class':'username-field'}),
        
        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Username or Email',
        widget=forms.TextInput(
            attrs = {
                'placeholder': 'username',
                'class':'username-email-login_field',
                'align':'center',
            }
        )
    )

    password = forms.CharField(
        label='Password', 
        widget=forms.PasswordInput(
            attrs = {
                'placeholder': 'password',
                'class':'password-login-field',
                'type':'password', 
                'align':'center', 


            }
        )
    )

class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(
        required=True,
        label="Username",
        widget=forms.TextInput(attrs={
            'class':'username', 
            'type':'text', 
            'align':'center', 
            'placeholder':'username'}),
    )
    email = forms.CharField(
        required=True,
        label="Email",
        widget=forms.EmailInput(attrs={
            'class':'email-field signup-fields', 
            'type':'email', 
            'align':'center', 
            'placeholder':'email'}),
    )
    
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']

class UpdateProfileForm(forms.ModelForm):
    image = forms.ImageField(
        required=False,     
        label = "Profile photo",
        help_text="change profile photo",
        widget=forms.FileInput(attrs={
            'class':'file-img'
            
        })
    )
    
    bio = forms.CharField(
        required=False,     
        widget=forms.Textarea(
            attrs={
                # 'id':'txtinput',
                'class':'edit-user-txtarea',
                'rows':5,
              
            }
        )
    )
    
    website = forms.URLField(
        label="",
        required=False,
        widget=forms.URLInput(attrs={
            'class':'', 
            'type':'url', 
            'align':'center', 
            'placeholder':'Website'}),
    )
    gender = forms.ChoiceField(
        required=False,    
        choices= GENDER,
        label="",
        widget=forms.Select(attrs={
            'class':'', 
            'type':'text', 
            'align':'center',}),
    )
    
    class Meta:
        model = UserProfile
        fields = ['image','bio','website','gender']
    


class ChangeUserPassword(PasswordChangeForm):
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'type':'password', 
            'align':'center', 
        }),
    )
    
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'type':'password', 
            'align':'center', 
           }),
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'type':'password', 
            'align':'center', 
        }),
    )
    
    class Meta:
        model = User
        fields = ['old_password','new_password1','new_password2']
    

users/views.py
from django.contrib import messages
from users.forms import LoginForm
from django.contrib.auth.models import User
from django.views.generic import DetailView
from django.contrib.auth.views import LoginView

from django.core.mail import BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.core.mail import EmailMultiAlternatives
from django import template

from django.contrib.auth import update_session_auth_hash

from django.shortcuts import get_object_or_404, redirect, render
from users.forms import RegisterForm,UpdateProfileForm,UpdateUserForm,ChangeUserPassword
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from shoes_app.models import Shoe

def sign_up(request):
      
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request,f'Your account with the username {username} has been created')
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request,'users/sign_up.html',{'form':form})


class Profile(LoginRequiredMixin,DetailView):
        
    template_name = 'users/user_profile.html'
    
    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['users'] = User.objects.all()
        context_data['shoes'] = Shoe.objects.all().order_by('-time_posted')
        return context_data

    def get_object(self):
           UserName= self.kwargs.get("username")
           return get_object_or_404(User, username=UserName)

  
class CustomLoginView(LoginView):
    template_name = 'login.html'
    form_class = LoginForm
    
@login_required
def update_profile(request,username):
    user = User.objects.get(username=username)
    
    if user.id != request.user.id:
        return redirect('index')
    
    if request.method == 'POST':    
        user_form = UpdateUserForm(request.POST,instance=user)
        profile_form = UpdateProfileForm(request.POST,request.FILES,
        instance=user.userprofile)
    
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request,'Profile has been updated successfully')
            return redirect('index')
    else:
        user_form = UpdateUserForm(instance=user)
        profile_form = UpdateProfileForm(instance=user.userprofile)
    
    return render(request,'users/update_profile.html',
    {'user_form':user_form, 'profile_form':profile_form})


def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data)|Q(username=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					plaintext = template.loader.get_template('users/password_reset_email.txt')
					htmltemp = template.loader.get_template('users/password_reset_email.html')
					c = { 
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					text_content = plaintext.render(c)
					html_content = htmltemp.render(c)
					try:
						msg = EmailMultiAlternatives(subject, text_content, 'Website <admin@example.com>', [user.email], headers = {'Reply-To': 'admin@example.com'})
						msg.attach_alternative(html_content, "text/html")
						msg.send()
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					messages.info(request, "Password reset instructions have been sent to the email address entered.")
					return redirect ("index")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="users/password_reset.html", context={"password_reset_form":password_reset_form})




@login_required
def change_password(request,username):
    
    user = User.objects.get(username=username)
    
    if user.id != request.user.id:
        return redirect('/')
    
    if request.method == 'POST':
        form = ChangeUserPassword(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('index')
    else:
        form = ChangeUserPassword(request.user)
    return render(request, 'users/change_password.html', {
        'form': form
    })


@login_required
def delete_user(request,username):
    user = User.objects.get(username=username)
    
    if user.id != request.user.id:
        return redirect('index')
    
    if request.method == 'GET':
        return redirect('index')
    
    if request.method == 'POST':
        user.delete()
        return redirect('index')
    
    return render(request,'users/delete_account.html',{'user':user})
    
    

users/templates/users/change_password.html
{% extends 'base.html' %} 
{% block head %}
{% load static %} {% load bootstrap5 %}
<link rel="stylesheet" href="{% static 'users/css/user-form.css' %}" />
{% endblock head %}

{% block title %}Change Password {{user.username}}{% endblock title %}  
{% block body %}
{% block navbar %}{% endblock navbar %}
{%block searchbox %} {% endblock searchbox %}

<div class="container login-container">
    <div class="div-contain-login">
      <h1>Change passowrd</h1>
      <form method="POST">
        {% csrf_token %}
  
        <div class="login-div">
          <div class="inner-login-div">
            <div class="inner-login-div">{% bootstrap_form form %}</div>
          </div>
        </div>
        <button type="submit" class="btn btn-dark login-btn">Change password</button>
      </form>


    </div>
  </div>



{% endblock body %}

users/templates/users/delete_account.html
<h1>Account has been deleted succesfully</h1>

users/templates/users/login.html
{% extends 'base.html' %} {% load socialaccount %} {% block head %}
{% load static %} {% load bootstrap5 %}
<link rel="stylesheet" href="{% static 'users/css/user-form.css' %}" />
{% endblock head %} 
{% block title %}Login{% endblock title %}  
{% block body %} {% block navbar %}{% endblock navbar %}
{%block searchbox %} {% endblock searchbox %}

<div class="container login-container">
  <div class="div-contain-login">
    <h1>Login</h1>
    <form method="POST">
      {% csrf_token %}

      <div class="login-div">
        <div class="inner-login-div">
          <div class="inner-login-div">{% bootstrap_form form %}</div>
        </div>
      </div>
      <button type="submit" class="btn btn-dark login-btn">Login</button>
    </form>
    <a
      class="btn btn-lg btn-google-login btn-block btn-outline"
      href="{% provider_login_url 'google' %}"
      ><img src="https://img.icons8.com/color/16/000000/google-logo.png" />
      Continue with Google</a
    >
    <br>
    <p><a href="{% url 'password_reset' %}" class="forgot-password"> Forgot password? </a> </p>
    <p class="text-inverse text-center">
      Don't have an account?
      <a href="<?= base_url() ?>auth/login" data-abc="true" class="signup">Signup</a>
    </p>
  </div>
</div>

 {% block footer %}{% endblock footer %} {% endblock body %}

users/templates/users/logout.html
{% extends 'base.html' %} 
{% block head %}
{% endblock head %}
{% block title %}Logged Out{% endblock title %}  
{% block body %}
<div class="container">
  <p>You have been logged out.Proceed to <a href="{% url 'login' %}">Login?</a></p>
</div>
{% endblock body %}

users/templates/users/password_reset.html
{% extends 'base.html' %} 
{% block head %}

{% load static %} {% load bootstrap5 %}
<link rel="stylesheet" href="{% static 'users/css/user-form.css' %}" />
{% endblock head %}

{% block title %}Reset Password {{user.username}}{% endblock title %}

{% block body %}
{% block navbar %}{% endblock navbar %}
{%block searchbox %} {% endblock searchbox %}

<div class="container login-container">
    <div class="div-contain-reset-password">
      <h1>Reset passowrd</h1>
      <form method="POST">
        {% csrf_token %}
  
        <div class="login-div">
          <div class="inner-login-div">
            <div class="inner-login-div">{% bootstrap_form password_reset_form %}</div>
          </div>
        </div>
        <button type="submit" class="btn btn-dark login-btn">Change password</button>
      </form>


    </div>
  </div>

 {% comment %} {% block footer %}{% endblock footer %} {% endcomment %}


{% endblock body %}

users/templates/users/password_reset_complete.html
{% extends "base.html" %} {% block body %}

<!--Password Reset Complete-->
<div class="container p-4">
  <h2 class="font-weight-bold mt-3">Password reset complete</h2>
  <hr />
  <p>Your password has been set. You may go ahead and log in now.</p>
  <a href="/login" class="btn btn-primary">Log in</a>
</div>

{% endblock body %}

users/templates/users/password_reset_confirm.html
{% extends "base.html" %} {% load static %} {% load bootstrap5 %} 
{% block body %}

<!--Password Reset Confirm-->
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Password Reset Confirm</h2>
  <hr />
  <p>Please enter your new password.</p>
  <form method="POST">
    {% csrf_token %} {% bootstrap_form form %}
    <button class="btn btn-primary" type="submit">Reset password</button>
  </form>
</div>

{% endblock body %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %} {% block body %}

<!--Password reset sent-->
<div class="container p-5">
  <h2 class="font-weight-bold mt-3">Password reset sent</h2>
  <hr />
  <p>
    We've emailed you instructions for setting your password, if an account
    exists with the email you entered. You should receive them shortly.<br />If
    you don't receive an email, please make sure you've entered the address you
    registered with, and check your spam folder.
  </p>
</div>

{% endblock body %}

users/templates/users/password_reset_email.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>HTML email template</title>
    <meta name="viewport" content="width = 375, initial-scale = -1">
  </head>

  <body style="background-color: #ffffff; font-size: 16px;">
    <center>
      <table align="center" border="0" cellpadding="0" cellspacing="0" style="height:100%; width:600px;">
          <!-- BEGIN EMAIL -->
          <tr>
            <td align="center" bgcolor="#ffffff" style="padding:30px">
               <p style="text-align:left">Hello,<br><br> We received a request to reset the password for your account for this email address. To initiate the password reset process for your account, click the link below.
              </p>
              <p>
                <a target="_blank" style="text-decoration:none; background-color: black; border: black 1px solid; color: #fff; padding:10px 10px; display:block;" href="{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}">
                  <strong>Reset Password</strong></a>
              </p>
              <p style="text-align:left">This link can only be used once. If you need to reset your password again, please visit <a href="{{ protocol }}://{{domain}}">postyourshoe.com</a> and request another reset.<br><br>If you did not make this request, you can simply ignore this email.</p>
              <p style="text-align:left">
              Sincerely,<br>Postyourshoes Team
              </p>
            </td>
          </tr>
        </tbody>
      </table>
    </center>
  </body>
</html>

users/templates/users/update_profile.html
{% extends 'base.html' %} {% load static %} {% load bootstrap5 %} 
{% block head %}

<link rel="stylesheet" href="{% static 'users/css/update-profile.css' %}" />

{% endblock head %}
{% block title %}Edit Profile - {{user.username}}{% endblock title %} 
 {% block body %} {% block searchbox %} 
{% endblock searchbox %}
<div class="vertical-rule"></div>

<div class="container update-profile-container form-control">
  <div class="left-hand-links">
    <a href="" style="text-decoration: none"
      ><h6 class="left-links-text">Edit profile</h6></a
    >
    <a
      href="{% url 'users:change_password' user.username %}"
      style="text-decoration: none"
      ><h6 class="left-links-text">Change password</h6></a
    >


    <button
    type="button"
    class="btn btn-secondary delete-btn"
    data-bs-toggle="modal"
    data-bs-target="#exampleModal"
  >
    Logout
  </button>

  <div
    class="modal fade"
    id="exampleModal"
    tabindex="-1"
    aria-labelledby="exampleModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">
            Logout of account {{user.username}}
          </h5>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          Are you sure you want to logout?
          <!-- <br>
        Action is not recoverable. -->
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            No
          </button>
          <form
            method="POST"
            action="{% url 'logout' %}"
          >
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Yes</button>
          </form>
        </div>
      </div>
    </div>
  </div>


<br class="button-br">

    <button
      type="button"
      class="btn btn-danger delete-btn"
      data-bs-toggle="modal"
      data-bs-target="#exampleModal2"
    >
      Delete account
    </button>

    <div
      class="modal fade"
      id="exampleModal2"
      tabindex="-1"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
              Delete account for {{user.username}}
            </h5>
            <button
              type="button"
              class="btn-close"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body">
            Are you sure you want to delete your account?
            <br />
            Deleting this account will result to deleting every post associated
            with this account. As such all shoe model posted by this account
            will be deleted.Your email and profile assoicated with this account
            will be deleted.
            <!-- <br>
          Action is not recoverable. -->
          </div>
          <div class="modal-footer">
            <button
              type="button"
              class="btn btn-secondary"
              data-bs-dismiss="modal"
            >
              No
            </button>
            <form
              method="POST"
              action="{% url 'users:delete_user' user.username %}"
            >
              {% csrf_token %}
              <button type="submit" class="btn btn-danger">Yes</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div>
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}

      <div class="update-profile-form">
        {% bootstrap_form user_form %} {% bootstrap_form profile_form %}
        <button type="submit" class="btn btn-secondary submit-form-btn">
          update profile
        </button>
      </div>
    </form>
  </div>
</div>
{% endblock body %}

users/templates/users/user_profile.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'users/css/user-profile.css' %}" />
{% endblock head %} 
{% block title %}@{{user.username}} Shoe photos{% endblock title %}
{% block body %} {% block navbar %}{% endblock navbar %} 
{% block searchbox %}{% endblock searchbox %}
<header>
  <div class="container">
    <div class="profile">
      <div class="profile-image">
        {% if user.userprofile.image %}

        <a href="">
          <img
            src="{{user.userprofile.image.url}}"
            width="152px"
            height="152px"
            alt=""
            class="profile-img"
          />
        </a>

        {% else %}
        <img
          src="{% static 'images/user_default_img.png' %}"
          width="152px"
          height="152px"
          alt=""
          class="profile-img"
        />

        {% endif %}
      </div>

      <div class="profile-user-settings">
        <h1 class="profile-user-name">{{user.username}}</h1>

        {% if request.user == user %}
        <a
          href="{% url 'users:update_profile' user.username %}"
          class="btn profile-edit-btn"
          >Edit Profile</a
        >
        {% else %}
        <a
          href="{% url 'users:update_profile' user.username %}"
          class="btn profile-edit-btn"
          style="display: none"
          >Edit Profile</a
        >

        {% endif %}
      </div>

      <div class="profile-bio">
        <span class="profile-real-name"
          >{{user.last_name}} {{user.first_name}}
        </span>
        <p>{{user.userprofile.bio}} 📷✈️🏕️</p>
        <h3><a href="">{{user.userprofile.website}}</a></h3>
      </div>
    </div>
    <!-- End of profile section -->
  </div>

  <!-- End of container -->
</header>

<main>
  <div class="container">
    <hr />

    <div class="div-above-hr">
      <h4><a href="" style="color: #000"> POSTS</a></h4>

      {% if request.user == user %}
      <h4><a href="{% url 'shoes_app:add_shoe' %}"> ADD SHOE</a></h4>

      {% else %}
      <h4 style="display: none">
        <a href="{% url 'shoes_app:add_shoe' %}">ADD SHOE</a>
      </h4>

      {% endif %}

    </div>

    <div class="gallery">
      {% for shoe in shoes %} {% if shoe.user == user %}

         {% if request.user != shoe.user %}

          <a href="{% url 'shoes_app:shoe_detail' shoe.slug  %}" >
        <div class="gallery-item" tabindex="0">
          <img
            src="{{shoe.image1.url}}"
            class="img-fluid gallery-image img-thumbnail"
            alt=""
          />

          <div class="gallery-item-info"></div>
        </div>
      </a>
      {% else %}
               
          
      <button
        type="button"
        class="btn"
        data-bs-toggle="modal"
        data-bs-target="#exampleModal"
      >
        <div class="gallery-item" tabindex="0">
          <img
            src="{{shoe.image1.url}}"
            class="img-fluid gallery-image img-thumbnail"
            alt=""
          />

          <div class="gallery-item-info"></div>
        </div>
      </button>

      <div
        class="modal fade"
        id="exampleModal"
        tabindex="-1"
        aria-labelledby="exampleModalLabel"
        aria-hidden="true"
      >
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h3
                class="modal-title"
                id="exampleModalLabel"
                style="text-transform: capitalize"
              >
                {{shoe.name}}
              </h3>
              <button
                type="button"
                class="btn-close"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
            </div>
            <div class="modal-body" style="text-align: center">
              <a
                href="{% url 'shoes_app:shoe_detail' shoe.slug  %}"
                style="text-decoration: none; color: blue"
              >
                <h3>View shoe</h3>
              </a>
              <hr />
              <a
                href="{% url 'shoes_app:edit_shoe' shoe.slug  %}"
                style="text-decoration: none; color: rgb(112, 112, 112)"
              >
                <h3>Edit shoe</h3>
              </a>

              <hr />

              <h3 style="text-decoration: none; color: red">
                <form
                  method="POST"
                  action="{% url 'shoes_app:delete_shoe' shoe.slug  %}"
                >
                  {% csrf_token %}
                  <button type="submit" class="btn btn-danger">
                    Delete Shoe
                  </button>
                </form>
              </h3>

     
            </div>
            <div class="modal-footer"></div>
          </div>
        </div>
      </div>


         {% endif %}

      {% else %}
      <a href="{% url 'shoes_app:shoe_detail' shoe.slug  %}" style="display:none">
        <div class="gallery-item" tabindex="0">
          <img
            src="{{shoe.image1.url}}"
            class="img-fluid gallery-image img-thumbnail"
            alt=""
          />

          <div class="gallery-item-info"></div>
        </div>
      </a>
      {% endif %} {% endfor %}
    </div>

 
  </div>

</main>
{% block footer %}{% endblock footer %} {% endblock body %}