shoes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views
from shoes_app import views
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls), 
    path("", views.index_page, name="index"),
    path("about/", views.about_us, name="about"),
    path("search/", views.search, name="search"),

    path('accounts/', include('allauth.urls')),
    path("signup/", user_views.sign_up, name="signup"),

    path ('login/',user_views.CustomLoginView.as_view(
    template_name='users/login.html'),name="login"),

    path("logout/", auth_views.LogoutView.as_view(
    template_name='users/logout.html'), name="logout"),
    
    path('men/',views.men_shoes_page,name="men"),
    path('women/',views.women_shoes_page,name="women"),
    
    path('boots/',views.boots_page,name="boots"),
    path('sneakers/',views.sneakers_shoe_page,name="sneakers"),
    path('sports/',views.sports_shoe_page,name="sports"),


    path("password-reset/", user_views.password_reset_request, name="password_reset"),
        
    path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(
    template_name='users/password_reset_done.html'
    ),name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    template_name="users/password_reset_confirm.html"
    ), name='password_reset_confirm'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
    template_name='users/password_reset_complete.html'
    ), name='password_reset_complete'),
    
    path("users/", include('users.urls')),
    path("shoes/", include('shoes_app.urls')),
        
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoes_app/urls.py
from django.urls import path
from shoes_app import views

app_name = 'shoes_app'

urlpatterns = [
    path('add-shoe/', views.AddShoe.as_view(), name='add_shoe'),
    path("<slug:slug>/", views.shoe_detail, name="shoe_detail"),
    path("<slug:slug>/edit-shoe/", views.edit_shoe, name="edit_shoe"),
    path('<slug:slug>/delete-shoe/', views.delete_shoe, name='delete_shoe'),

]

users/urls.py
from django.urls import path,include
from users import views as user_views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [  
    path('<str:username>/',user_views.Profile.as_view(),name="user_profile"),
    path('<str:username>/update-profile/',user_views.update_profile,name='update_profile'),
    path('<str:username>/change-password/', user_views.change_password, name='change_password'),
    path('<str:username>/delete-account/', user_views.delete_user, name='delete_user'),
    
]

templates/about_us.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/about_us.css' %}" />
{% endblock head %} 
{% block title %}About us{% endblock title %}
{% block body %} {% block searchbox %} 
{% endblock searchbox %}

<section>
  <div class="container">
    <div class="about-us">
      <div class="each-div">
        <h1 class="heading">About us</h1>
        <p class="about-text">
          Have a business or brand that deals with selling shoes? Don't have
          enough capital to start up your website?. Don't worry Postyourshoes has
          you covered. Postyourshoes is a website that deals with the posting of
          shoe products for businesses, organizations or individuals so anyone
          around the world can see and patronize your business. When we say
          posting, what that simply means is putting your shoe brand or business
          out to the world.
          <br />
          You don't have to worry about any kind of payments as this is totally
          free and available to anyone around the world. We won't and will never
          ask for your card details.
          <br />
          We can also help you locate your favorite shoes. The more users posts
          their shoe products, the more it is easier for you to find that shoe
          you saw in your various stores.
          <br />
          There is also no limit to the number of shoe products that can be
          posted here on our website. This might be the turning point in your
          website why don't you join us right now. We'll be happy to have you as
          one of our most appreciated users.
          <br />
          NOTE shoes can not be sold from this website as this is just a website
          to help put your business out to the world.
        </p>
      </div>

      <div class="each-div">
        <h1 class="heading">Posting shoes</h1>
        <p class="about-text">
          Posting shoes is a very simple procedure. All you really need to do is
          <a href="{% url 'signup' %}">signup</a> using our form or using your google accounts. If
          you already have an account, you can simply <a href="{% url 'login' %}">Login</a> and
          continue. Note you won't be able to post any shoes if you are not
          signed in or you don't have an account. This is to avoid unauthorized
          access to your shoe products and to have each user relationships with
          shoes each particular shoe they have posted or removed.
          <br />
          After authenticating your password you can either tap the link on the
          navigation bar or go to your user profile account and tap on the ADD
          SHOE link there. You will be prompted to a form which you are going to
          fill. Note, not all fields are required in the form but it is much
          better to fill the whole form as this will enhance better experince
          with other users when they look at the details of your shoe. The
          fields in the form are fields like the name of the shoe, the shoe
          brand, some images which are gotten from the user filling the form,
          price you would like to sell the shoe, your brand social media
          accounts. E.g Instagram,Twitter,Facebook accounts etc.
          <br />
          After filling the form you would see the shoe appear on your profile
          page and in the category you selected when filling the form. You can
          then click on the image to see the full detail of the shoe you just
          created.
        </p>
      </div>

      <div class="each-div">
        <h1 class="heading">Edit shoe</h1>
        <p class="about-text">
          If you want to make changes to a shoe you have already posted all you
          need to do is go to your profile page and click on the EDIT SHOE LINK
          and you will be directed to the form you used to add a shoe but this
          time the form will already be filled with the previous information you
          have already filled about that shoe.
          <br />
          You can also delete a shoe. Go to the EDIT SHOE link and scroll down.
          There is a delete shoe button there and it will handle the removal of
          that shoe model. Note every information about that shoe will be
          deleteed.The images,social media accounts etc. Think very well before
          deleting a shoe as this process cannot be restored.
        </p>
      </div>

      <div class="each-div">
        <h1 class="heading">User profile</h1>
        <p class="about-text">
          Your user profile is where you can access and edit all your related
          data. Your profile is automatically created for you after signing up.
          You can access your profile by clicking on the user profile icon in
          the navigation bar.
          <br />
          You can edit your profile by clicking on the edit profile button in
          your user profile page. Data like your profile image, email, username,
          changing your password, deleting your account etc. can be edited by
          you in your user profile. Logging out of your account can also be done
          from our profile.
        </p>
      </div>

      <div class="each-div">
        <h1 class="heading">Privacy policy</h1>
        <p class="about-text">
          We don't give out any information you have filled in the form out to
          any user. We only require your email for resetting your password if
          needed and sending you updates on our website when needed. NOTE no
          information can be accessed by any user apart from you. That is why we
          don't ask for your phone number when filling out your form as we don't
          want unwanted user access using your phone numbers for malicious
          activities. Your profile can only be edited by you and no one else.
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock body %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
    
    {% block title %}{% endblock title %}

    </title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://code.jquery.com/jquery-3.6.0.js"
      integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
      crossorigin="anonymous"
    ></script>
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/master.css' %}" />
    {% block head %}{% endblock head %}
  </head>
  <body>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container-fluid">
        

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a href="{% url 'about' %}" 
              class="nav-link {% if request.path == '/about/' %} active {%endif%}">
              ABOUT</a>
            </li>
          </ul>

          <ul class="navbar-nav mx-auto">
            <li id="home" class="nav-item">
              <a
                class="nav-link {% if request.path == '/' %} active {%endif%}"
                aria-current="page"
                href="{% url 'index' %}"
                >HOME</a
              >
            </li>
            <li id="men" class="nav-item">
              <a class="nav-link 
            {% if request.path == '/men/' %} active {%endif%}" 
            href="{% url 'men' %}">MEN</a>
            </li>

            <li id="women" class="nav-item">
              <a class="nav-link 
            {% if request.path == '/women/' %} active {%endif%}" 
            href="{% url 'women' %}">WOMEN</a>
            </li>

            <li id="boot" class="nav-item">
              <a class="nav-link 
            {% if request.path == '/boots/' %} active {%endif%}" 
            href="{% url 'boots' %}">BOOTS</a>
            </li>

            <li id="sneakers" class="nav-item">
              <a class="nav-link 
            {% if request.path == '/sneakers/' %} active {%endif%}" 
            href="{% url 'sneakers' %}">SNEAKERS</a>
            </li>

            <li id="sport" class="nav-item">
              <a class="nav-link {% if request.path == '/sports/' %} active {%endif%}" 
              href="{% url 'sports' %}">SPORTS</a>
            </li>

          </ul>

          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item" style="display: none">
              <a href="" class="nav-link">SIGN UP</a>
            </li>

            {% if request.user == user %}
            <li class="nav-item">
              <a href="{% url 'shoes_app:add_shoe' %}" 
              class="nav-link {% if request.path == '/shoes/add-shoe/' %} active {%endif%}"
                >ADD SHOE</a
              >
            </li>
            {% else %}

            <li class="nav-item" style="display: none">
              <a href="{% url 'shoes_app:add_shoe' %}" class="nav-link"
                >ADD SHOE</a
              >
            </li>
            {% endif %} {% else %}
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link">LOGIN</a>
            </li>
            <li class="nav-item">
              <a href="{% url 'signup' %}" class="nav-link">SIGN UP</a>
            </li>
            {% endif %}

            <li class="nav-item">
              {% if user.is_authenticated %}
              <a
                href="{% url 'users:user_profile' user.username  %}"
                class="nav-link"
                ><i class="fas fa-user-circle fa-2x"></i
              ></a>

              {% else %}

              <a href="" class="nav-link" style="display: none"
                ><i class="fas fa-user-circle fa-2x"></i
              ></a>

              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
    {% endblock navbar %} {% if messages %} {% for message in messages %}
    <div
      class="alert alert-{{message.tags}} alert-dismissible fade show text-center"
      role="alert"
    >
      {{message}}
      <button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    {% endfor %} {% endif %} {% block searchbox %}
    
    <div class="main">
      <!-- Actual search box -->
      <div class="form-group has-search">
        <span class="fa fa-search form-control-feedback"></span>
         <form action="{% url 'search' %}" method="POST">
         {% csrf_token %}
           <input type="search" class="form-control" name="search" placeholder="Search shoes, users" />
         </form>
         
      </div>
    </div>
  
    
    {% endblock searchbox %} {% block body %}{% endblock body %} 
    {% block footer %}

    <div class="footer-dark">
      <footer>
        <div class="container">
          <div class="row">
            <div class="col-sm-6 col-md-3 item">
              <h3>Quick links</h3>
              <ul>
                <li><a href="{% url 'index' %}">HOME</a></li>
                {% if user.is_authenticated %}
                <li style="display:none"><a href="{% url 'login' %}">LOGIN</a></li>
                {% else %}    
                <li><a href="{% url 'login' %}">LOGIN</a></li>
                {% endif %}
                {% if user.is_authenticated %}
                <li style="display:none"><a href="{% url 'signup' %}">SIGN UP</a></li>
                {% else %}    
                <li><a href="{% url 'signup' %}">SIGN UP</a></li>
                {% endif %}
                <li><a href="{% url 'men' %}">MEN</a></li>
                <li><a href="{% url 'women' %}">WOMEN</a></li>
                <li><a href="{% url 'boots' %}">BOOTS</a></li>
                <li><a href="{% url 'sneakers' %}">SNEAKERS</a></li>
                <li><a href="{% url 'sports' %}">SPORTS</a></li>
              </ul>
            </div>
            <div class="col-sm-6 col-md-3 item">
              <h3>About</h3>
              <ul>
                <li><a href="{% url 'about' %}">About us</a></li>
                <!-- <li><a href="#">Contact us</a></li>
                <li><a href="#">Careers</a></li> -->
              </ul>
            </div>
            <div class="col-md-6 item text">
              <h3>Postyourshoes</h3>
              <p>
                Postyourshoes is a website that helps individuals or
                organizations that deal with shoe business,post their 
                shoes here on our website. Absolutely easy!. Sign up
                and get started.
              </p>
            </div>
            <div class="col item social">
              <a href="https://github.com/Obike-dev"><i class="fab fa-github fa-lg"></i></a
              ><a href="https://www.linkedin.com/in/bright-obike-808853220/"><i class="fab fa-linkedin-in fa-lg"></i></a
              ><a href="https://www.upwork.com/freelancers/~01fe41db41c9742464"
                ><img
                  src="{% static 'images/icons/upwork-icon-4.png' %}"
                  alt=""
                  class="upwork-icon"
              /></a>
              <!-- <a href="#"><i class="icon ion-social-instagram"></i></a> -->
            </div>
          </div>
          <p class="copyright">postyourshoes © 2021</p>
        </div>
      </footer>
    </div>
    {% endblock footer %}
    <script>
      $(document).ready(function () {
        window.setTimeout(function () {
          $('.alert')
            .fadeTo(500, 0)
            .slideUp(500, function () {
              $(this).remove();
            });
        }, 5000);

      });

      $('body').append(
        '<div style="" id="loadingDiv"><div class="loader">Loading...</div></div>'
      );
      $(window).on('load', function () {
        setTimeout(removeLoader, 2000); //wait for page load PLUS two seconds.
      });
      function removeLoader() {
        $('#loadingDiv').fadeOut(500, function () {
          // fadeOut complete. Remove the loading div
          $('#loadingDiv').remove(); //makes page more lightweight
        });
      }

    </script>

  </body>
</html>

<!-- <i class="icon ion-social-snapchat"></i> -->

templates/index.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}" />
{% endblock head %} 
{% block title %}Postyourshoes{% endblock title %}  

{% block body %}

<section>
  <div class="top-heading">
    <h4 class="intro-text">
      BEST SHOES
      <br />
      FOR
      <br />
      EVERYONE.
    </h4>
    {% if user.is_authenticated %}
    <div class="button-div" style="display: none">
      <a href="{% url 'signup' %}" class="btn btn-dark button-txt">Sign Up</a>
    </div>
    {% else %}

    <div class="button-div">
      <a href="{% url 'signup' %}" class="btn btn-dark button-txt">Sign Up</a>
    </div>
    {% endif %}

    <div>
      <img
        class="top-image"
        src="/static/images/shoe_images/Churchs-Bletsoe-Jodhpur-Boot-2.jpg"
        alt=""
      />
    </div>
  </div>
</section>

<div
  id="carouselExampleIndicators"
  class="carousel slide carousel-div"
  data-bs-ride="carousel"
>
  <div class="carousel-indicators">
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-bs-target="#carouselExampleIndicators"
      data-bs-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="static/images/shoe_images/grey-shoe.webp"
        class="d-block w-100 carousel-div"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="static/images/shoe_images/32080694_image_750x920.jpg"
        class="d-block w-100 carousel-div"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="static/images/shoe_images/louis-v.jpg"
        class="d-block w-100 carousel-div"
        alt="..."
      />
    </div>
  </div>
</div>

<div class="container shoe-container">
  <div class="row">
    {% for each_sneakers in sneakers|slice:"3" %}
    <div class="col-lg-4 col-md-4 col-12 shoe-card">
      <a
        href="{% url 'shoes_app:shoe_detail' each_sneakers.slug %}"
        style="text-decoration: none"
      >
        <img
          src="{{each_sneakers.image1.url}}"
          alt=""
          class="shoe-img img-thumbnail"
          style="margin-bottom: 0%"
        />
        <div>
          <p style="margin-bottom: 0%; color: #000; text-transform: capitalize">
            {{each_sneakers.name}}
          </p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<!-- </div>
</div> -->

<div class="">
  <h4 class="something-good som-good">
    FIND YOUR POTENTIAL <br />
    CUSTOMERS HERE
  </h4>
  <p class="shoes-p">find customers at postyourshoes.online</p>
</div>

<div class="third-section"></div>

<div>
  <h4 class="third-sec-text">
    POST YOUR SHOES <br />
    SIGN UP NOW
    <div>
      <a href="{% url 'about' %}" class="btn btn-dark learn-more-btn"
        >Learn more</a
      >
    </div>
  </h4>
</div>

<div class="container shoe-container-2">
  <div class="row">
    {% for shoe in women_shoes|slice:"3" %}
    <div class="col-lg-4 col-md-4 col-12 shoe-card">
      <a
        href="{% url 'shoes_app:shoe_detail' shoe.slug %}"
        style="text-decoration: none"
      >
        <img
          src="{{shoe.image1.url}}"
          alt=""
          class="shoe-img img-thumbnail"
          style="margin-bottom: 0%"
        />
        <div>
          <p style="margin-bottom: 0%; color: #000; text-transform: capitalize">
            {{shoe.name}}
          </p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<section>
  <h4 class="discover">
    LET OTHERS DISCOVER <br />
    WHAT YOU HAVE
  </h4>
  <div class="end-div">
    <h3 class="div-text">
      Have shoes to sell ? <br />
      We'll be happy to post <br />
      them here for you. <br />
    </h3>
  </div>
</section>

<div class="container shoe-container last-shoes-con" style="margin-top: 100px">
  <div class="row">
    {% for boot in boots|slice:"3" %}
    <div class="col-lg-4 col-md-4 col-12 shoe-card">
      <a
        href="{% url 'shoes_app:shoe_detail' boot.slug %}"
        style="text-decoration: none"
      >
        <img
          src="{{boot.image1.url}}"
          alt=""
          class="shoe-img img-thumbnail"
          style="margin-bottom: 0%"
        />
        <div>
          <p style="margin-bottom: 0%; color: #000; text-transform: capitalize">
            {{boot.name}}
          </p>
        </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>

<!-- last-img -->
{% endblock body %} {% block script %} $(document).ready(function () { $(".nav
li").removeClass("active"); }); {% endblock script %}

templates/search.html
{% extends 'base.html' %} {% load static %} {% block head %}
<link
  rel="stylesheet"
  href="{% static 'shoes_app/css/shoe-categories.css' %}"
/>
{% endblock head %} 
{% block title %}Search Result{% endblock title %}  
{% block body %}

<div class="container shoe-container">
  <div class="row">
    {% if search %} {% for shoe in shoes %}
    <div class="col-lg-4 col-md-6 col-12 shoe-card">
      <a
        href="{% url 'shoes_app:shoe_detail' shoe.slug %}"
        style="text-decoration: none"
      >
        <img
          src="{{shoe.image1.url}}"
          alt=""
          class="shoe-img img-thumbnail"
          style="margin-bottom: 0%"
        />
        <div>
          <p style="margin-bottom: 0%; color: #000; text-transform: capitalize">
            {{shoe.name}}
          </p>
          {% if shoe.shop_name %}
          <p style="margin-top: 0%; color: grey; text-transform: capitalize">
            posted by: {{shoe.shop_name}}
          </p>
          {% else %}
          <p style="margin-top: 0%; color: grey; text-transform: capitalize">
            posted by: {{shoe.user.username}}
          </p>

          {% endif %}
        </div>
      </a>
    </div>
    {% endfor %} {% for user in users %}

    <div class="col-lg-4 col-md-6 col-12 shoe-card">
      <a
        href="{% url 'users:user_profile' user.username %}"
        style="text-decoration: none"
      >
        <img
          src="{{user.userprofile.image.url}}"
          alt=""
          class="shoe-img img-thumbnail"
          style="margin-bottom: 0%"
        />
        <div>
          <p style="margin-bottom: 0%; color: #000;">
            {{user.username}}
          </p>
        </div>
      </a>
    </div>
    {% endfor %} {% endif %}
  </div>
</div>

{% endblock body %}